# Generated by Django 5.0 on 2024-03-24 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qr_api_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QRCode',
        ),
    ]
